return {
  plenary = { src = "https://github.com/nvim-lua/plenary.nvim" },
  nui = { src = "https://github.com/MunifTanjim/nui.nvim" },
  lazydev = { src = "https://github.com/folke/lazydev.nvim" },
  ["mini-icons"] = { src = "https://github.com/nvim-mini/mini.icons" },
  catppuccin = { src = "https://github.com/catppuccin/nvim", name = "catppuccin" },
  ["which-key"] = { src = "https://github.com/folke/which-key.nvim" },
  dressing = { src = "https://github.com/stevearc/dressing.nvim" },
  hlslens = { src = "https://github.com/kevinhwang91/nvim-hlslens" },
  diagflow = { src = "https://github.com/dgagn/diagflow.nvim" },
  ["nvim-navic"] = { src = "https://github.com/SmiteshP/nvim-navic" },
  noice = { src = "https://github.com/folke/noice.nvim" },
  notify = { src = "https://github.com/rcarriga/nvim-notify" },
  lualine = { src = "https://github.com/nvim-lualine/lualine.nvim" },
  ["mini-starter"] = { src = "https://github.com/nvim-mini/mini.starter" },
  ["mini-indentscope"] = { src = "https://github.com/nvim-mini/mini.indentscope" },
  ["mini-hipatterns"] = { src = "https://github.com/nvim-mini/mini.hipatterns" },
  ["mini-tabline"] = { src = "https://github.com/nvim-mini/mini.tabline" },
  statuscol = { src = "https://github.com/luukvbaal/statuscol.nvim" },
  ["fold-cycle"] = { src = "https://github.com/jghauser/fold-cycle.nvim" },
  helpview = { src = "https://github.com/OXY2DEV/helpview.nvim" },
  ufo = { src = "https://github.com/kevinhwang91/nvim-ufo" },
  ["promise-async"] = { src = "https://github.com/kevinhwang91/promise-async" },
  lensline = { src = "https://github.com/oribarilan/lensline.nvim" },
  triforce = { src = "https://github.com/gisketch/triforce.nvim" },
  volt = { src = "https://github.com/nvzone/volt" },
  haunt = { src = "https://github.com/TheNoeTrevino/haunt.nvim" },
  snacks = { src = "https://github.com/folke/snacks.nvim" },
  ["neural-open"] = { src = "https://github.com/dtormoen/neural-open.nvim" },
  oil = { src = "https://github.com/stevearc/oil.nvim" },
  yazi = { src = "https://github.com/mikavilpas/yazi.nvim" },
  ["mini-visits"] = { src = "https://github.com/nvim-mini/mini.visits" },
  ["mini-comment"] = { src = "https://github.com/nvim-mini/mini.comment" },
  ["mini-surround"] = { src = "https://github.com/nvim-mini/mini.surround" },
  ["mini-ai"] = { src = "https://github.com/nvim-mini/mini.ai" },
  ["todo-comments"] = { src = "https://github.com/folke/todo-comments.nvim" },
  spectre = { src = "https://github.com/nvim-pack/nvim-spectre" },
  refactoring = { src = "https://github.com/ThePrimeagen/refactoring.nvim" },
  flash = { src = "https://github.com/folke/flash.nvim" },
  blink = { src = "https://github.com/saghen/blink.cmp", version = "1.*" },
  copilot = { src = "https://github.com/zbirenbaum/copilot.lua" },
  supermaven = { src = "https://github.com/supermaven-inc/supermaven-nvim" },
  sidekick = { src = "https://github.com/folke/sidekick.nvim" },
  mcphub = { src = "https://github.com/ravitemer/mcphub.nvim" },
  vectorcode = { src = "https://github.com/Davidyz/VectorCode", version = "*" },
  neogen = { src = "https://github.com/danymat/neogen" },
  ensure = { src = "https://github.com/noirbizarre/ensure.nvim" },
  mason = { src = "https://github.com/williamboman/mason.nvim" },
  schemastore = { src = "https://github.com/b0o/SchemaStore.nvim", name = "SchemaStore.nvim" },
  ["mason-lspconfig"] = { src = "https://github.com/williamboman/mason-lspconfig.nvim" },
  ["mason-nvim-dap"] = { src = "https://github.com/jay-babu/mason-nvim-dap.nvim" },
  lspconfig = { src = "https://github.com/neovim/nvim-lspconfig" },
  conform = { src = "https://github.com/stevearc/conform.nvim" },
  lint = { src = "https://github.com/mfussenegger/nvim-lint" },
  trouble = { src = "https://github.com/folke/trouble.nvim" },
  treesitter = { src = "https://github.com/nvim-treesitter/nvim-treesitter", version = "main" },
  ["treesitter-textobjects"] = { src = "https://github.com/nvim-treesitter/nvim-treesitter-textobjects" },
  ["treesitter-context"] = { src = "https://github.com/nvim-treesitter/nvim-treesitter-context" },
  rustaceanvim = { src = "https://github.com/mrcjkb/rustaceanvim" },
  ["ts-error-translator"] = { src = "https://github.com/dmmulroy/ts-error-translator.nvim" },
  gopher = { src = "https://github.com/olexsmir/gopher.nvim" },
  jira = { src = "https://github.com/letieu/jira.nvim" },
  dap = { src = "https://github.com/mfussenegger/nvim-dap" },
  ["dap-go"] = { src = "https://github.com/leoluz/nvim-dap-go" },
  ["dap-virtual-text"] = { src = "https://github.com/theHamsta/nvim-dap-virtual-text" },
  ["dap-view"] = { src = "https://github.com/igorlfs/nvim-dap-view" },
  nio = { src = "https://github.com/nvim-neotest/nvim-nio" },
  ["mini-sessions"] = { src = "https://github.com/nvim-mini/mini.sessions" },
  ["mini-operators"] = { src = "https://github.com/nvim-mini/mini.operators" },
  qf = { src = "https://github.com/ten3roberts/qf.nvim" },
  focus = { src = "https://github.com/beauwilliams/focus.nvim" },
  kulala = { src = "https://github.com/mistweaverco/kulala.nvim" },
  dbee = { src = "https://github.com/kndndrj/nvim-dbee", name = "nvim-dbee" },
  overseer = { src = "https://github.com/stevearc/overseer.nvim", version = "v1.6.0" },
  neotest = { src = "https://github.com/nvim-neotest/neotest" },
  ["neotest-go"] = { src = "https://github.com/nvim-neotest/neotest-go" },
  ["neotest-phpunit"] = { src = "https://github.com/olimorris/neotest-phpunit" },
  ["neovim-tips"] = { src = "https://github.com/saxon1964/neovim-tips" },
  ["zellij-nav"] = { src = "https://github.com/swaits/zellij-nav.nvim" },
  dooing = { src = "https://github.com/atiladefreitas/dooing" },
  store = { src = "https://github.com/alex-popov-tech/store.nvim" },
  ["mini-diff"] = { src = "https://github.com/nvim-mini/mini.diff" },
  neogit = { src = "https://github.com/NeogitOrg/neogit" },
  diffview = { src = "https://github.com/sindrets/diffview.nvim" },
  codediff = { src = "https://github.com/esmuellert/codediff.nvim" },
  markview = { src = "https://github.com/OXY2DEV/markview.nvim" },
  obsidian = { src = "https://github.com/obsidian-nvim/obsidian.nvim", version = "*" },
  spider = { src = "https://github.com/chrisgrieser/nvim-spider" },
}
