local runtime = require("config.pack_runtime")
local snacks = require("config.snacks")

local M = {}

function M.setup()
  vim.g.loaded_netrwPlugin = 1

  local load_neural_open = runtime.once(function()
    runtime.load("neural-open")
    require("neural-open").setup({})
  end)

  local load_oil = runtime.once(function()
    runtime.load("oil")
    require("oil").setup({
      default_file_explorer = false,
      view_options = {
        show_hidden = true,
      },
    })
  end)

  local load_yazi = runtime.once(function()
    runtime.load_many({ "plenary", "yazi" })
    require("yazi").setup({
      open_for_directories = true,
      open_multiple_tabs = true,
      keymaps = { show_help = "<f1>" },
    })
  end)

  local load_visits = runtime.once(function()
    runtime.load("mini-visits")
    require("mini.visits").setup()
  end)

  load_neural_open()
  load_yazi()
  runtime.defer(load_visits)

  local function snacks_picker(method, opts)
    return function()
      snacks.picker(method, opts)
    end
  end

  vim.keymap.set("n", "<leader><space>", "<Plug>(NeuralOpen)", { desc = "Find smart files" })
  vim.keymap.set("n", "<leader>,", snacks_picker("buffers"), { desc = "Buffers" })
  vim.keymap.set("n", "<leader>/", snacks_picker("grep"), { desc = "Grep" })
  vim.keymap.set("n", "<leader>:", snacks_picker("command_history"), { desc = "Command history" })
  vim.keymap.set("n", "<leader>bb", snacks_picker("buffers"), { desc = "Buffer list" })
  vim.keymap.set("n", "<leader>bn", "<cmd>bnext<cr>", { desc = "Buffer next" })
  vim.keymap.set("n", "<leader>bp", "<cmd>bprevious<cr>", { desc = "Buffer previous" })
  vim.keymap.set("n", "<leader>fc", function()
    snacks.picker("files", { cwd = vim.fn.stdpath("config") })
  end, { desc = "Find config" })
  vim.keymap.set("n", "<leader>ff", snacks_picker("files"), { desc = "Find files" })
  vim.keymap.set("n", "<leader>fg", snacks_picker("grep"), { desc = "Find grep" })
  vim.keymap.set("n", "<leader>fr", snacks_picker("recent"), { desc = "Find recent" })
  vim.keymap.set("n", "<leader>fp", snacks_picker("projects"), { desc = "Find projects" })
  vim.keymap.set("n", "<leader>fb", snacks_picker("buffers"), { desc = "Find buffers" })
  vim.keymap.set("n", "<leader>fh", snacks_picker("help"), { desc = "Find help" })
  vim.keymap.set("n", "<leader>sa", snacks_picker("autocmds"), { desc = "Search autocmds" })
  vim.keymap.set("n", "<leader>sb", snacks_picker("lines"), { desc = "Search buffer lines" })
  vim.keymap.set("n", "<leader>sB", snacks_picker("grep_buffers"), { desc = "Search open buffers" })
  vim.keymap.set("n", "<leader>sc", snacks_picker("command_history"), { desc = "Search command history" })
  vim.keymap.set("n", "<leader>sC", snacks_picker("commands"), { desc = "Search commands" })
  vim.keymap.set("n", "<leader>sk", snacks_picker("keymaps"), { desc = "Search keymaps" })
  vim.keymap.set("n", "<leader>sd", snacks_picker("diagnostics"), { desc = "Search diagnostics" })
  vim.keymap.set("n", "<leader>sD", snacks_picker("diagnostics_buffer"), { desc = "Search buffer diagnostics" })
  vim.keymap.set("n", "<leader>sg", snacks_picker("grep"), { desc = "Search grep" })
  vim.keymap.set("n", "<leader>sh", snacks_picker("help"), { desc = "Search help" })
  vim.keymap.set("n", "<leader>sj", snacks_picker("jumps"), { desc = "Search jumps" })
  vim.keymap.set("n", "<leader>sl", snacks_picker("loclist"), { desc = "Search location list" })
  vim.keymap.set("n", "<leader>sm", snacks_picker("marks"), { desc = "Search marks" })
  vim.keymap.set("n", "<leader>sq", snacks_picker("qflist"), { desc = "Search quickfix" })
  vim.keymap.set("n", "<leader>sR", snacks_picker("resume"), { desc = "Search resume" })
  vim.keymap.set({ "n", "x" }, "<leader>sw", snacks_picker("grep_word"), { desc = "Search word" })
  vim.keymap.set("n", "<leader>ss", snacks_picker("lsp_symbols"), { desc = "Search symbols" })
  vim.keymap.set("n", "<leader>sS", snacks_picker("lsp_workspace_symbols"), { desc = "Search workspace symbols" })
  vim.keymap.set("n", "<leader>gb", snacks_picker("git_branches"), { desc = "Git branches" })
  vim.keymap.set("n", "<leader>gs", snacks_picker("git_status"), { desc = "Git status" })
  vim.keymap.set("n", "<leader>gl", snacks_picker("git_log"), { desc = "Git log" })
  vim.keymap.set("n", "<leader>gL", snacks_picker("git_log_line"), { desc = "Git log line" })
  vim.keymap.set("n", "<leader>gf", snacks_picker("git_log_file"), { desc = "Git log file" })
  vim.keymap.set("n", "<leader>gS", snacks_picker("git_stash"), { desc = "Git stash" })
  vim.keymap.set("n", "<leader>bd", function()
    snacks.bufdelete()
  end, { desc = "Buffer delete" })
  vim.keymap.set("n", "<leader>bD", function()
    snacks.bufdelete({ force = true })
  end, { desc = "Buffer delete force" })
  vim.keymap.set({ "n", "t" }, "<C-/>", function()
    snacks.terminal()
  end, { desc = "Toggle terminal" })
  vim.keymap.set({ "n", "t" }, "<C-_>", function()
    snacks.terminal()
  end, { desc = "Toggle terminal" })
  vim.keymap.set("n", "<leader>.", function()
    snacks.scratch()
  end, { desc = "Scratch toggle" })
  vim.keymap.set("n", "<leader>S", function()
    snacks.scratch_select()
  end, { desc = "Scratch select" })
  vim.keymap.set({ "n", "t" }, "<leader>cn", function()
    snacks.words_jump(vim.v.count1)
  end, { desc = "Code next reference" })
  vim.keymap.set({ "n", "t" }, "<leader>cp", function()
    snacks.words_jump(-vim.v.count1)
  end, { desc = "Code prev reference" })
  vim.keymap.set("n", "<leader>uC", function()
    snacks.picker("colorschemes")
  end, { desc = "Colorschemes" })

  vim.keymap.set("n", "<leader>-", function()
    load_oil()
    vim.cmd.Oil()
  end, { desc = "Open Oil at the current file" })

  vim.keymap.set({ "n", "v" }, "-", function()
    load_yazi()
    vim.cmd.Yazi()
  end, { desc = "Open yazi at the current file" })

  vim.keymap.set("n", "<leader>vy", function()
    load_visits()
    require("mini.visits").add_label("core")
  end, { desc = "Visits: add 'core' label" })
  vim.keymap.set("n", "<leader>vd", function()
    load_visits()
    require("mini.visits").delete_label("core")
  end)
  vim.keymap.set("n", "<leader>vY", function()
    load_visits()
    require("mini.visits").select_path(nil, { filter = "core" })
  end, { desc = "Visits: select 'core' (cwd)" })
  vim.keymap.set("n", "<leader>v1", function()
    load_visits()
    require("mini.visits").iterate_paths("first", vim.fn.getcwd(), { filter = "core", wrap = true })
  end, { desc = "Visits first" })
  vim.keymap.set("n", "<leader>v2", function()
    load_visits()
    require("mini.visits").iterate_paths("backward", vim.fn.getcwd(), { filter = "core", wrap = true })
  end, { desc = "Visits backward" })
  vim.keymap.set("n", "<leader>v3", function()
    load_visits()
    require("mini.visits").iterate_paths("forward", vim.fn.getcwd(), { filter = "core", wrap = true })
  end, { desc = "Visits forward" })
  vim.keymap.set("n", "<leader>v4", function()
    load_visits()
    require("mini.visits").iterate_paths("last", vim.fn.getcwd(), { filter = "core", wrap = true })
  end, { desc = "Visits last" })
end

return M
